### ISSUE TITLE
API: Profile Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#1]
## Acceptance Criteria
- A new profile instance is created when a new user object is created;
- It's possible to edit the profile information;
- API responds with a 200 status code and all created profiles;

## Tasks
- [x] Create the profile model;
- [x] Add a post_save method to listen for a user creation signal;
- [x] Create the profile serializer;
- [x] Create the profile list view;
- [x] Create the profile detail view;
- [x] Add the profile urls.
