### ISSUE TITLE
API: Quote Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#2]
## Acceptance Criteria
- Possible to create a new quote instance from the API interface;
- It's possible to edit the quote object;
- API responds with a 200 status code and displays all quotes;

## Tasks
- [x] Create the quote model;
- [x] Create the quote serializer;
- [x] Create the quote list view;
- [x] Create the quote detail view;
- [x] Add the quote urls.

**Comment by andrebraga7** [comment]
All done.
