### ISSUE TITLE
API: Quote mode

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#2]
## Acceptance Criteria
- Possible to create a new quote instance from the API interface;
- It's possible to edit the quote object;
- API responds with a 200 status code and displays all quotes;

## Tasks
- [ ] Create the quote model;
- [ ] Create the quote serializer;
- [ ] Create the quote list view;
- [ ] Create the quote detail view;
- [ ] Add the quote urls.
