### ISSUE TITLE
API: Author Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#3]
## Acceptance Criteria
- A new author object is created when a new quote object is created if it does not already exist;
- It's possible to edit the author object;
- API responds with a 200 status code and displays all authors;

## Tasks
- [x] Create the author model;
- [x] Add a perform_create method to get or create a new author when creating or updating a quote;
- [x] Create the author serializer;
- [x] Create the author list view;
- [x] Create the author detail view;
- [x] Add the author urls.

**Comment by andrebraga7** [comment]
Done and working when creating and updating a quote.
