### ISSUE TITLE
API: Like Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#4]
## Acceptance Criteria
- Possible to create a new like instance from the API interface;
- It's possible to delete the like object;
- API responds with a 200 status code and displays all likes;

## Tasks
- [x] Create the like model;
- [x] Create the like serializer;
- [x] Create the like list view;
- [x] Create the like detail view;
- [x] Add the like urls.
