### ISSUE TITLE
API: Save Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#5]
## Acceptance Criteria
- Possible to create a new save instance from the API interface;
- It's possible to edit the save object;
- API responds with a 200 status code and displays all save objects;

## Tasks
- [ ] Create the save model;
- [ ] Create the save serializer;
- [ ] Create the save list view;
- [ ] Create the save detail view;
- [ ] Add the save urls.
