### ISSUE TITLE
API: Save Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#5]
## Acceptance Criteria
- Possible to create a new save instance from the API interface;
- It's possible to edit the save object;
- API responds with a 200 status code and displays all save objects;

## Tasks
- [x] Create the save model;
- [x] Create the save serializer;
- [x] Create the save list view;
- [x] Create the save detail view;
- [x] Add the save urls.

**Comment by andrebraga7** [comment]
Perfect
