### ISSUE TITLE
API: Comment Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#6]
## Acceptance Criteria
- Possible to create a new comment instance from the API interface;
- It's possible to edit the comment object;
- API responds with a 200 status code and displays all comments;

## Tasks
- [x] Create the comment model;
- [x] Create the comment serializer;
- [x] Create the comment list view;
- [x] Create the comment detail view;
- [x] Add the comment urls.
