### ISSUE TITLE
API: Reply Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#7]
## Acceptance Criteria
- Possible to create a new reply instance from the API interface;
- It's possible to edit the reply object;
- API responds with a 200 status code and displays all replies;

## Tasks
- [x] Create the reply model;
- [x] Create the reply serializer;
- [x] Create the reply list view;
- [x] Create the reply detail view;
- [x] Add the reply urls.

**Comment by andrebraga7** [comment]
Done.
