### ISSUE TITLE
API: Reply Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#7]
## Acceptance Criteria
- Possible to create a new reply instance from the API interface;
- It's possible to edit the reply object;
- API responds with a 200 status code and displays all replies;

## Tasks
- [ ] Create the reply model;
- [ ] Create the reply serializer;
- [ ] Create the reply list view;
- [ ] Create the reply detail view;
- [ ] Add the reply urls.
