### ISSUE TITLE
API: Follower Model

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme-api#8]
## Acceptance Criteria
- Possible to create a new follower instance from the API interface;
- It's possible to edit the follower object;
- API responds with a 200 status code and displays all followers;

## Tasks
- [ ] Create the follower model;
- [ ] Create the follower serializer;
- [ ] Create the follower list view;
- [ ] Create the follower detail view;
- [ ] Add the follower urls.

**Comment by andrebraga7** [comment]
Complete
